// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "antidote",
  "name": "Antidote",
  "durationMs": 4000,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [],
    "objects": [
      {
        "id": "obj_bfd29ox0",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "e4",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "snd_8f2jiijt",
        "name": "SFX",
        "keys": [
          {
            "id": "sdk_6y3q6bxe",
            "timeMs": 0,
            "soundId": "arcana:antidote",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "evt_tl2sqy6s",
        "name": "Events",
        "keys": []
      }
    ]
  },
  "meta": {
    "source": "arcana-studio",
    "createdAt": 1776207228366,
    "updatedAt": 1776207504952,
    "usedPieces": [],
    "isCutscene": false,
    "canAnimatePiece": true,
    "cardPiecePreview": null,
    "rarity": "common",
    "category": "utility",
    "soundId": "arcana:antidote"
  },
  "description": "Select a poisoned piece to cleanse it and prevent its death. Can only target pieces with active poison."
};
