// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "astral_rebirth",
  "name": "astral rebirth",
  "durationMs": 4700,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [
      {
        "id": "cam_main",
        "name": "Main Camera",
        "keys": [
          {
            "id": "camk_0xdzifds",
            "timeMs": 0,
            "position": [
              0.5886595662321794,
              2.128425281199444,
              2.6389798287100352
            ],
            "target": [
              0.5022784619714433,
              -0.1705358944558453,
              0.17451771598505292
            ],
            "rotation": [
              -0.7506680165628902,
              0.025624625771474705,
              0.023896638563664037
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "camk_72z5sfmt",
            "timeMs": 800,
            "position": [
              0.5886595662317241,
              2.12842528119943,
              2.6389798287100636
            ],
            "target": [
              0.5022784619714433,
              -0.1705358944558453,
              0.17451771598505292
            ],
            "rotation": [
              -0.7506680165628812,
              0.025624625771339626,
              0.0238966385635377
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "camk_2g82awbu",
            "timeMs": 2200,
            "position": [
              0.5657765112164085,
              1.5194118226300635,
              1.986123829801761
            ],
            "target": [
              0.5022784619714433,
              -0.1705358944558453,
              0.17451771598505292
            ],
            "rotation": [
              -0.7506680165628815,
              0.02562462577133969,
              0.023896638563537787
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          }
        ]
      }
    ],
    "objects": [
      {
        "id": "obj_ovv87bm5",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "e4",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "legacy_sound",
        "name": "Legacy Sound",
        "keys": [
          {
            "id": "snd_0",
            "timeMs": 0,
            "soundId": "arcana:astral_rebirth_materialize",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_1",
            "timeMs": 800,
            "soundId": "arcana:astral_rebirth_energy",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_2",
            "timeMs": 1600,
            "soundId": "arcana:astral_rebirth_complete",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "legacy_events",
        "name": "Legacy Events",
        "keys": [
          {
            "id": "evt_0_0",
            "timeMs": 0,
            "type": "camera_move",
            "delayMs": 0,
            "payload": {
              "phase": "camera_focus",
              "cardId": "astral_rebirth",
              "legacyAction": "camera_move",
              "soundMap": {
                "materialize": "arcana:astral_rebirth_materialize",
                "glow": "arcana:astral_rebirth_energy",
                "complete": "arcana:astral_rebirth_complete"
              }
            }
          },
          {
            "id": "evt_0_1",
            "timeMs": 0,
            "type": "sound_materialize",
            "delayMs": 0,
            "payload": {
              "phase": "camera_focus",
              "cardId": "astral_rebirth",
              "legacyAction": "sound_materialize",
              "soundId": "arcana:astral_rebirth_materialize",
              "soundMap": {
                "materialize": "arcana:astral_rebirth_materialize",
                "glow": "arcana:astral_rebirth_energy",
                "complete": "arcana:astral_rebirth_complete"
              }
            }
          },
          {
            "id": "evt_1_0",
            "timeMs": 800,
            "type": "vfx_astral_particles",
            "delayMs": 0,
            "payload": {
              "phase": "materialize",
              "cardId": "astral_rebirth",
              "legacyAction": "vfx_astral_particles",
              "soundMap": {
                "materialize": "arcana:astral_rebirth_materialize",
                "glow": "arcana:astral_rebirth_energy",
                "complete": "arcana:astral_rebirth_complete"
              }
            }
          },
          {
            "id": "evt_1_1",
            "timeMs": 800,
            "type": "vfx_spiral_glow",
            "delayMs": 0,
            "payload": {
              "phase": "materialize",
              "cardId": "astral_rebirth",
              "legacyAction": "vfx_spiral_glow",
              "soundMap": {
                "materialize": "arcana:astral_rebirth_materialize",
                "glow": "arcana:astral_rebirth_energy",
                "complete": "arcana:astral_rebirth_complete"
              }
            }
          },
          {
            "id": "evt_1_2",
            "timeMs": 800,
            "type": "overlay_yellow_flash",
            "delayMs": 0,
            "payload": {
              "phase": "materialize",
              "cardId": "astral_rebirth",
              "legacyAction": "overlay_yellow_flash",
              "soundMap": {
                "materialize": "arcana:astral_rebirth_materialize",
                "glow": "arcana:astral_rebirth_energy",
                "complete": "arcana:astral_rebirth_complete"
              }
            }
          },
          {
            "id": "evt_1_3",
            "timeMs": 800,
            "type": "sound_glow",
            "delayMs": 0,
            "payload": {
              "phase": "materialize",
              "cardId": "astral_rebirth",
              "legacyAction": "sound_glow",
              "soundId": "arcana:astral_rebirth_energy",
              "soundMap": {
                "materialize": "arcana:astral_rebirth_materialize",
                "glow": "arcana:astral_rebirth_energy",
                "complete": "arcana:astral_rebirth_complete"
              }
            }
          },
          {
            "id": "evt_3_0",
            "timeMs": 2200,
            "type": "sound_complete",
            "delayMs": 0,
            "payload": {
              "phase": "camera_return",
              "cardId": "astral_rebirth",
              "legacyAction": "sound_complete",
              "soundId": "arcana:astral_rebirth_complete",
              "soundMap": {
                "materialize": "arcana:astral_rebirth_materialize",
                "glow": "arcana:astral_rebirth_energy",
                "complete": "arcana:astral_rebirth_complete"
              }
            }
          }
        ]
      }
    ]
  },
  "meta": {
    "source": "legacy-import",
    "createdAt": 1775976464184,
    "updatedAt": 1775976808129,
    "usedPieces": [],
    "legacyId": "astral_rebirth",
    "legacyImportedAt": 1775976464184,
    "legacyConfigSnapshot": {
      "id": "astral_rebirth",
      "duration": 4700,
      "config": {
        "camera": {
          "targetZoom": 1.6,
          "duration": 600,
          "holdDuration": 1600,
          "easing": "easeInOutCubic",
          "shots": [
            {
              "zoom": 1.95,
              "duration": 380,
              "holdDuration": 320,
              "returnDuration": 320,
              "offset": [
                2.5,
                3.3,
                1.9
              ],
              "lookAtYOffset": 0.34
            },
            {
              "zoom": 1.7,
              "duration": 460,
              "holdDuration": 520,
              "returnDuration": 380,
              "offset": [
                -2.3,
                3.5,
                -1.8
              ],
              "lookAtYOffset": 0.3
            },
            {
              "zoom": 1.45,
              "duration": 520,
              "holdDuration": 680,
              "returnDuration": 460,
              "offset": [
                0,
                5.2,
                0.1
              ],
              "lookAtYOffset": 0.28
            }
          ]
        },
        "overlay": {
          "effect": "flash",
          "color": "#ffeb3b",
          "duration": 1200,
          "intensity": 0.5,
          "fadeIn": 300,
          "hold": 600,
          "fadeOut": 300
        },
        "vfx": {
          "astralParticles": 64,
          "glowColor": "#ffeb3b",
          "glowIntensity": 1.2,
          "materializeDuration": 1000,
          "spiralEffect": true
        },
        "sound": {
          "materialize": "arcana:astral_rebirth_materialize",
          "glow": "arcana:astral_rebirth_energy",
          "complete": "arcana:astral_rebirth_complete"
        },
        "phases": [
          {
            "name": "camera_focus",
            "duration": 600,
            "actions": [
              "camera_move",
              "sound_materialize"
            ]
          },
          {
            "name": "materialize",
            "duration": 1000,
            "actions": [
              "vfx_astral_particles",
              "vfx_spiral_glow",
              "overlay_yellow_flash",
              "sound_glow"
            ],
            "delay": 200
          },
          {
            "name": "hold",
            "duration": 600,
            "actions": []
          },
          {
            "name": "camera_return",
            "duration": 600,
            "actions": [
              "sound_complete"
            ]
          }
        ]
      }
    },
    "isCutscene": true,
    "canAnimatePiece": true,
    "rarity": "legendary",
    "category": "resurrection",
    "soundId": "arcana:astral_rebirth"
  },
  "description": "Resurrect up to 2 captured pieces onto your back rank. Higher-value pieces are revived first."
};
