// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "fog_of_war",
  "name": "Fog of War",
  "durationMs": 4000,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [],
    "objects": [
      {
        "id": "obj_gjc0kyfg",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "e4",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "snd_kigg9mnl",
        "name": "SFX",
        "keys": [
          {
            "id": "sdk_86n5t3ml",
            "timeMs": 0,
            "soundId": "arcana:whoosh",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "evt_gkosf6tv",
        "name": "Events",
        "keys": []
      }
    ]
  },
  "meta": {
    "source": "arcana-studio",
    "createdAt": 1776207693561,
    "updatedAt": 1776207989841,
    "usedPieces": [],
    "isCutscene": false,
    "canAnimatePiece": false,
    "cardPiecePreview": null,
    "rarity": "uncommon",
    "category": "utility",
    "soundId": "arcana:fog_of_war"
  },
  "description": "Hide your piece positions from opponent for one turn."
};
