// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "mind_control",
  "name": "mind control",
  "durationMs": 2000,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [
      {
        "id": "cam_k429jjcz",
        "name": "Main Camera",
        "keys": [
          {
            "id": "camk_ek3nqpyu",
            "timeMs": 0,
            "position": [
              -2.6053080230430043e-20,
              1.7524086281971831,
              1.7524086281971818
            ],
            "target": [
              0,
              0.15,
              0
            ],
            "rotation": [
              -0.7853981633974487,
              -1.0512565052071502e-20,
              -1.051256505207151e-20
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "camk_7vsbf57m",
            "timeMs": 1100,
            "position": [
              1.7987702543814434,
              1.467213326276585,
              -0.8680913704839975
            ],
            "target": [
              0,
              0.15,
              0
            ],
            "rotation": [
              -2.1050608716790586,
              0.8122169245251142,
              2.254717565390436
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          }
        ]
      }
    ],
    "objects": [
      {
        "id": "obj_psc0sazq",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "e4",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "legacy_sound",
        "name": "Legacy Sound",
        "keys": [
          {
            "id": "snd_0",
            "timeMs": 0,
            "soundId": "arcana:mind_control_take",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_1",
            "timeMs": 600,
            "soundId": "arcana:mind_control_release",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "legacy_events",
        "name": "Legacy Events",
        "keys": [
          {
            "id": "evt_0_0",
            "timeMs": 0,
            "type": "vfx:play",
            "delayMs": 0,
            "payload": {
              "phase": "control_activate",
              "cardId": "mind_control",
              "legacyAction": "vfx_purple_aura",
              "effect": "purple_aura",
              "durationMs": 900,
              "soundMap": {
                "control": "arcana:mind_control_take",
                "release": "arcana:mind_control_release"
              }
            }
          },
          {
            "id": "evt_0_1",
            "timeMs": 0,
            "type": "overlay:vignette",
            "delayMs": 0,
            "payload": {
              "phase": "control_activate",
              "cardId": "mind_control",
              "legacyAction": "overlay_vignette",
              "duration": 700,
              "soundMap": {
                "control": "arcana:mind_control_take",
                "release": "arcana:mind_control_release"
              }
            }
          },
          {
            "id": "evt_0_2",
            "timeMs": 0,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "control_activate",
              "cardId": "mind_control",
              "legacyAction": "sound_control",
              "soundId": "arcana:mind_control_take",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "control": "arcana:mind_control_take",
                "release": "arcana:mind_control_release"
              }
            }
          }
        ]
      }
    ]
  },
  "meta": {
    "source": "legacy-import",
    "createdAt": 1776119567209,
    "updatedAt": 1776119794253,
    "usedPieces": [],
    "legacyId": "mind_control",
    "legacyImportedAt": 1776119567209,
    "legacyConfigSnapshot": {
      "id": "mind_control",
      "duration": 3400,
      "config": {
        "camera": {
          "targetZoom": 2.2,
          "duration": 320,
          "holdDuration": 1200,
          "easing": "easeInOutCubic",
          "shots": [
            {
              "zoom": 2.65,
              "duration": 220,
              "holdDuration": 200,
              "returnDuration": 220,
              "offset": [
                1.2,
                2.2,
                0.8
              ],
              "lookAtYOffset": 0.28
            },
            {
              "zoom": 2.45,
              "duration": 260,
              "holdDuration": 260,
              "returnDuration": 220,
              "offset": [
                -1.1,
                2.3,
                -0.7
              ],
              "lookAtYOffset": 0.28
            },
            {
              "zoom": 2.7,
              "duration": 220,
              "holdDuration": 240,
              "returnDuration": 220,
              "offset": [
                0.2,
                2.6,
                0
              ],
              "lookAtYOffset": 0.32
            }
          ]
        },
        "overlay": {
          "effect": "vignette",
          "color": "#9c27b0",
          "duration": 1200,
          "intensity": 0.6,
          "fadeIn": 300,
          "hold": 600,
          "fadeOut": 300
        },
        "vfx": {
          "auraColor": "#9c27b0",
          "auraIntensity": 0.9,
          "auraDuration": 1200,
          "controlParticles": 24,
          "pulseEffect": true
        },
        "sound": {
          "control": "arcana:mind_control_take",
          "release": "arcana:mind_control_release"
        },
        "phases": [
          {
            "name": "control_activate",
            "duration": 600,
            "actions": [
              "vfx_purple_aura",
              "overlay_vignette",
              "sound_control"
            ],
            "delay": 0
          },
          {
            "name": "control_active",
            "duration": 600,
            "actions": [],
            "delay": 0
          }
        ]
      }
    },
    "isCutscene": true,
    "canAnimatePiece": true,
    "rarity": "legendary",
    "category": "utility",
    "soundId": "arcana:mind_control"
  },
  "description": "Select an enemy piece to seize control of it. On your next move, you can only move that piece. It cannot capture the king."
};
