// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "pot_of_greed",
  "name": "Pot of Greed",
  "durationMs": 4000,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [],
    "objects": [
      {
        "id": "obj_2m63wcwe",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "center",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "snd_yzd11za0",
        "name": "SFX",
        "keys": [
          {
            "id": "sdk_p34zf1a4",
            "timeMs": 0,
            "soundId": "arcana:pot_of_greed",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "evt_j1bp8irt",
        "name": "Events",
        "keys": []
      }
    ]
  },
  "meta": {
    "source": "arcana-studio",
    "createdAt": 1776465397006,
    "updatedAt": 1776465474220,
    "usedPieces": [],
    "isCutscene": false,
    "canAnimatePiece": true,
    "cardPiecePreview": null,
    "rarity": "epic",
    "category": "utility",
    "soundId": "arcana:pot_of_greed"
  },
  "description": "Draw 3 additional cards from your deck. (\"That's what it does\")"
};
