// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "promotion_ritual",
  "name": "promotion ritual",
  "durationMs": 3620,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [
      {
        "id": "cam_main",
        "name": "Main Camera",
        "keys": [
          {
            "id": "cam_key_0",
            "timeMs": 0,
            "position": [
              2,
              3.6,
              1
            ],
            "target": [
              0,
              0.38,
              0
            ],
            "rotation": [
              0,
              0,
              0
            ],
            "fov": 29,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "cam_key_1",
            "timeMs": 920,
            "position": [
              0,
              6.2,
              6
            ],
            "target": [
              0,
              0.3,
              0
            ],
            "rotation": [
              0,
              0,
              0
            ],
            "fov": 36,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "cam_key_2",
            "timeMs": 2380,
            "position": [
              -2.4,
              3.8,
              -1.3
            ],
            "target": [
              0,
              0.34,
              0
            ],
            "rotation": [
              0,
              0,
              0
            ],
            "fov": 32,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "cam_key_3",
            "timeMs": 3620,
            "position": [
              1.7,
              4.2,
              -1.8
            ],
            "target": [
              0,
              0.24,
              0
            ],
            "rotation": [
              0,
              0,
              0
            ],
            "fov": 27,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          }
        ]
      }
    ],
    "objects": [
      {
        "id": "obj_9ce9civf",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "e4",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "legacy_sound",
        "name": "Legacy Sound",
        "keys": [
          {
            "id": "snd_0",
            "timeMs": 0,
            "soundId": "arcana:promotion_ritual_light",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_1",
            "timeMs": 800,
            "soundId": "arcana:promotion_ritual_transform",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_2",
            "timeMs": 1400,
            "soundId": "arcana:promotion_ritual_complete",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "legacy_events",
        "name": "Legacy Events",
        "keys": [
          {
            "id": "evt_0_0",
            "timeMs": 0,
            "type": "camera:focus",
            "delayMs": 0,
            "payload": {
              "phase": "camera_focus",
              "cardId": "promotion_ritual",
              "legacyAction": "camera_move",
              "anchor": "target",
              "duration": 600,
              "holdDuration": 1600,
              "returnDuration": 600,
              "lookAtYOffset": 0.38,
              "soundMap": {
                "lightImpact": "arcana:promotion_ritual_light",
                "transform": "arcana:promotion_ritual_transform",
                "complete": "arcana:promotion_ritual_complete"
              }
            }
          },
          {
            "id": "evt_1_0",
            "timeMs": 800,
            "type": "vfx:play",
            "delayMs": 0,
            "payload": {
              "phase": "light_strike",
              "cardId": "promotion_ritual",
              "legacyAction": "vfx_light_beam",
              "effect": "light_beam",
              "durationMs": 900,
              "soundMap": {
                "lightImpact": "arcana:promotion_ritual_light",
                "transform": "arcana:promotion_ritual_transform",
                "complete": "arcana:promotion_ritual_complete"
              }
            }
          },
          {
            "id": "evt_1_1",
            "timeMs": 800,
            "type": "overlay:monochrome",
            "delayMs": 0,
            "payload": {
              "phase": "light_strike",
              "cardId": "promotion_ritual",
              "legacyAction": "overlay_monochrome",
              "duration": 700,
              "soundMap": {
                "lightImpact": "arcana:promotion_ritual_light",
                "transform": "arcana:promotion_ritual_transform",
                "complete": "arcana:promotion_ritual_complete"
              }
            }
          },
          {
            "id": "evt_1_2",
            "timeMs": 800,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "light_strike",
              "cardId": "promotion_ritual",
              "legacyAction": "sound_light_impact",
              "soundId": "arcana:promotion_ritual_light",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "lightImpact": "arcana:promotion_ritual_light",
                "transform": "arcana:promotion_ritual_transform",
                "complete": "arcana:promotion_ritual_complete"
              }
            }
          },
          {
            "id": "evt_2_0",
            "timeMs": 1400,
            "type": "overlay:flash",
            "delayMs": 0,
            "payload": {
              "phase": "promotion",
              "cardId": "promotion_ritual",
              "legacyAction": "vfx_promotion_flash",
              "duration": 420,
              "soundMap": {
                "lightImpact": "arcana:promotion_ritual_light",
                "transform": "arcana:promotion_ritual_transform",
                "complete": "arcana:promotion_ritual_complete"
              }
            }
          },
          {
            "id": "evt_2_1",
            "timeMs": 1400,
            "type": "overlay:flash",
            "delayMs": 0,
            "payload": {
              "phase": "promotion",
              "cardId": "promotion_ritual",
              "legacyAction": "vfx_promotion_glow",
              "duration": 420,
              "soundMap": {
                "lightImpact": "arcana:promotion_ritual_light",
                "transform": "arcana:promotion_ritual_transform",
                "complete": "arcana:promotion_ritual_complete"
              }
            }
          },
          {
            "id": "evt_2_2",
            "timeMs": 1400,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "promotion",
              "cardId": "promotion_ritual",
              "legacyAction": "sound_transform",
              "soundId": "arcana:promotion_ritual_transform",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "lightImpact": "arcana:promotion_ritual_light",
                "transform": "arcana:promotion_ritual_transform",
                "complete": "arcana:promotion_ritual_complete"
              }
            }
          },
          {
            "id": "evt_4_0",
            "timeMs": 2800,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "camera_return",
              "cardId": "promotion_ritual",
              "legacyAction": "sound_complete",
              "soundId": "arcana:promotion_ritual_complete",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "lightImpact": "arcana:promotion_ritual_light",
                "transform": "arcana:promotion_ritual_transform",
                "complete": "arcana:promotion_ritual_complete"
              }
            }
          }
        ]
      }
    ]
  },
  "meta": {
    "source": "legacy-import",
    "createdAt": 1776121797901,
    "updatedAt": 1776122383220,
    "usedPieces": [],
    "legacyId": "promotion_ritual",
    "legacyImportedAt": 1776121797901,
    "legacyConfigSnapshot": {
      "id": "promotion_ritual",
      "duration": 5000,
      "config": {
        "camera": {
          "targetZoom": 1.5,
          "duration": 600,
          "holdDuration": 1600,
          "easing": "easeInOutCubic",
          "shots": [
            {
              "zoom": 2.05,
              "duration": 340,
              "holdDuration": 280,
              "returnDuration": 300,
              "offset": [
                2,
                3.6,
                1
              ],
              "lookAtYOffset": 0.38
            },
            {
              "zoom": 1.65,
              "duration": 520,
              "holdDuration": 520,
              "returnDuration": 420,
              "offset": [
                0,
                6.2,
                0
              ],
              "lookAtYOffset": 0.3
            },
            {
              "zoom": 1.9,
              "duration": 420,
              "holdDuration": 460,
              "returnDuration": 360,
              "offset": [
                -2.4,
                3.8,
                -1.3
              ],
              "lookAtYOffset": 0.34
            },
            {
              "zoom": 2.2,
              "duration": 320,
              "holdDuration": 300,
              "returnDuration": 300,
              "offset": [
                1.7,
                4.2,
                -1.8
              ],
              "lookAtYOffset": 0.24
            }
          ]
        },
        "overlay": {
          "effect": "monochrome",
          "duration": 2200,
          "intensity": 0.9,
          "fadeIn": 400,
          "hold": 1400,
          "fadeOut": 400
        },
        "vfx": {
          "lightBeam": true,
          "beamDuration": 800,
          "beamColor": "#ffeb3b",
          "beamIntensity": 1.3,
          "promotionFlash": true,
          "promotionParticles": 40,
          "glowColor": "#ffeb3b",
          "glowIntensity": 1.2
        },
        "sound": {
          "lightImpact": "arcana:promotion_ritual_light",
          "transform": "arcana:promotion_ritual_transform",
          "complete": "arcana:promotion_ritual_complete"
        },
        "phases": [
          {
            "name": "camera_focus",
            "duration": 600,
            "actions": [
              "camera_move"
            ]
          },
          {
            "name": "light_strike",
            "duration": 800,
            "actions": [
              "vfx_light_beam",
              "overlay_monochrome",
              "sound_light_impact"
            ],
            "delay": 200
          },
          {
            "name": "promotion",
            "duration": 600,
            "actions": [
              "vfx_promotion_flash",
              "vfx_promotion_glow",
              "sound_transform"
            ],
            "delay": 0
          },
          {
            "name": "hold",
            "duration": 800,
            "actions": []
          },
          {
            "name": "camera_return",
            "duration": 600,
            "actions": [
              "sound_complete"
            ]
          }
        ]
      }
    },
    "isCutscene": true,
    "canAnimatePiece": true,
    "rarity": "legendary",
    "category": "transformation",
    "soundId": "arcana:promotion_ritual"
  },
  "description": "Select a pawn and promote it to a queen. You gain 2 consecutive moves."
};
