// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "shield_pawn",
  "name": "Shield Pawn",
  "durationMs": 750,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true,
    "previewMode": "plane"
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [],
    "objects": [
      {
        "id": "obj_hggrnt0x",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "center",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [
          {
            "id": "objk_xic3xf5g",
            "timeMs": 0,
            "position": [
              0,
              0,
              0
            ],
            "rotation": [
              0,
              0,
              0
            ],
            "scale": [
              1,
              1,
              1
            ],
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ]
          },
          {
            "id": "objk_nimioqi4",
            "timeMs": 250,
            "position": [
              0,
              0,
              0
            ],
            "rotation": [
              0,
              0,
              0
            ],
            "scale": [
              1,
              1.8387580364245322,
              1
            ],
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ]
          },
          {
            "id": "objk_qmyj09fi",
            "timeMs": 500,
            "position": [
              0,
              -0.019059644181221858,
              0
            ],
            "rotation": [
              0,
              0,
              0
            ],
            "scale": [
              1,
              0.7967598550732244,
              1
            ],
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ]
          },
          {
            "id": "objk_fhf7khs2",
            "timeMs": 750,
            "position": [
              0,
              0,
              0
            ],
            "rotation": [
              0,
              0,
              0
            ],
            "scale": [
              1,
              1,
              1
            ],
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ]
          }
        ],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "snd_18mf7h68",
        "name": "SFX",
        "keys": [
          {
            "id": "sdk_t9sqjosl",
            "timeMs": 500,
            "soundId": "arcana:shield",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "evt_g86c6qj6",
        "name": "Events",
        "keys": []
      }
    ]
  },
  "meta": {
    "source": "arcana-studio",
    "createdAt": 1775802796896,
    "updatedAt": 1776283510623,
    "usedPieces": [],
    "isCutscene": false,
    "canAnimatePiece": true,
    "cardPiecePreview": null,
    "rarity": "common",
    "category": "defense",
    "soundId": "arcana:shield"
  },
  "description": "Select a pawn to grant temporary protection: it cannot be captured for one enemy turn."
};
