// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "time_travel",
  "name": "time travel",
  "durationMs": 6100,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [
      {
        "id": "cam_q5rfdyb0",
        "name": "Main Camera",
        "keys": [
          {
            "id": "camk_cu26nvqs",
            "timeMs": 0,
            "position": [
              -0.22910568143891144,
              6.818670211521936,
              7.831979757917323
            ],
            "target": [
              -0.15716658545547738,
              0.4927172451545865,
              -0.3808914636838315
            ],
            "rotation": [
              -0.6563347978101477,
              -0.00693931389720591,
              -0.005344903361850803
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "camk_6oxre0vb",
            "timeMs": 6100,
            "position": [
              -6.590295487396414,
              11.6930827203852,
              6.936709014358271
            ],
            "target": [
              -0.15716658545547738,
              0.4927172451545865,
              -0.3808914636838315
            ],
            "rotation": [
              -0.9920796068233774,
              -0.4482030433244964,
              -0.5856566126581824
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          }
        ]
      }
    ],
    "objects": [
      {
        "id": "obj_q51e60hh",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "e4",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "legacy_sound",
        "name": "Legacy Sound",
        "keys": [
          {
            "id": "snd_0",
            "timeMs": 0,
            "soundId": "arcana:time_travel_warp",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_1",
            "timeMs": 1200,
            "soundId": "arcana:time_travel_rewind",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_2",
            "timeMs": 2400,
            "soundId": "arcana:time_travel_complete",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "legacy_events",
        "name": "Legacy Events",
        "keys": [
          {
            "id": "evt_0_0",
            "timeMs": 0,
            "type": "camera:focus",
            "delayMs": 0,
            "payload": {
              "phase": "camera_ascend",
              "cardId": "time_travel",
              "legacyAction": "camera_move",
              "anchor": "target",
              "duration": 800,
              "holdDuration": 2000,
              "returnDuration": 800,
              "lookAtYOffset": 0.1,
              "soundMap": {
                "timewarp": "arcana:time_travel_warp",
                "rewind": "arcana:time_travel_rewind",
                "complete": "arcana:time_travel_complete"
              }
            }
          },
          {
            "id": "evt_0_1",
            "timeMs": 0,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "camera_ascend",
              "cardId": "time_travel",
              "legacyAction": "sound_timewarp",
              "soundId": "arcana:time_travel_warp",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "timewarp": "arcana:time_travel_warp",
                "rewind": "arcana:time_travel_rewind",
                "complete": "arcana:time_travel_complete"
              }
            }
          },
          {
            "id": "evt_1_0",
            "timeMs": 1200,
            "type": "vfx:play",
            "delayMs": 0,
            "payload": {
              "phase": "rewind_pieces",
              "cardId": "time_travel",
              "legacyAction": "vfx_afterimage_trails",
              "effect": "afterimage_trails",
              "durationMs": 900,
              "soundMap": {
                "timewarp": "arcana:time_travel_warp",
                "rewind": "arcana:time_travel_rewind",
                "complete": "arcana:time_travel_complete"
              }
            }
          },
          {
            "id": "evt_1_1",
            "timeMs": 1200,
            "type": "overlay:flash",
            "delayMs": 0,
            "payload": {
              "phase": "rewind_pieces",
              "cardId": "time_travel",
              "legacyAction": "vfx_rewind_animation",
              "duration": 420,
              "soundMap": {
                "timewarp": "arcana:time_travel_warp",
                "rewind": "arcana:time_travel_rewind",
                "complete": "arcana:time_travel_complete"
              }
            }
          },
          {
            "id": "evt_1_2",
            "timeMs": 1200,
            "type": "overlay:monochrome",
            "delayMs": 0,
            "payload": {
              "phase": "rewind_pieces",
              "cardId": "time_travel",
              "legacyAction": "overlay_monochrome",
              "duration": 700,
              "soundMap": {
                "timewarp": "arcana:time_travel_warp",
                "rewind": "arcana:time_travel_rewind",
                "complete": "arcana:time_travel_complete"
              }
            }
          },
          {
            "id": "evt_1_3",
            "timeMs": 1200,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "rewind_pieces",
              "cardId": "time_travel",
              "legacyAction": "sound_rewind",
              "soundId": "arcana:time_travel_rewind",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "timewarp": "arcana:time_travel_warp",
                "rewind": "arcana:time_travel_rewind",
                "complete": "arcana:time_travel_complete"
              }
            }
          },
          {
            "id": "evt_2_0",
            "timeMs": 2400,
            "type": "overlay:color-fade",
            "delayMs": 0,
            "payload": {
              "phase": "color_restore",
              "cardId": "time_travel",
              "legacyAction": "overlay_color_restore",
              "duration": 700,
              "soundMap": {
                "timewarp": "arcana:time_travel_warp",
                "rewind": "arcana:time_travel_rewind",
                "complete": "arcana:time_travel_complete"
              }
            }
          },
          {
            "id": "evt_3_0",
            "timeMs": 3200,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "camera_return",
              "cardId": "time_travel",
              "legacyAction": "sound_complete",
              "soundId": "arcana:time_travel_complete",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "timewarp": "arcana:time_travel_warp",
                "rewind": "arcana:time_travel_rewind",
                "complete": "arcana:time_travel_complete"
              }
            }
          }
        ]
      }
    ]
  },
  "meta": {
    "source": "legacy-import",
    "createdAt": 1776121797901,
    "updatedAt": 1776122462788,
    "usedPieces": [],
    "legacyId": "time_travel",
    "legacyImportedAt": 1776121797901,
    "legacyConfigSnapshot": {
      "id": "time_travel",
      "duration": 6100,
      "config": {
        "camera": {
          "targetZoom": 0.8,
          "duration": 800,
          "holdDuration": 2000,
          "easing": "easeInOutCubic",
          "cameraHeight": 25,
          "shots": [
            {
              "zoom": 1.18,
              "duration": 420,
              "holdDuration": 340,
              "returnDuration": 380,
              "offset": [
                5,
                6.2,
                3.9
              ],
              "lookAtYOffset": 0.1
            },
            {
              "zoom": 0.98,
              "duration": 520,
              "holdDuration": 520,
              "returnDuration": 420,
              "offset": [
                -4.7,
                6,
                -4.3
              ],
              "lookAtYOffset": 0.1
            },
            {
              "zoom": 0.82,
              "duration": 600,
              "holdDuration": 860,
              "returnDuration": 540,
              "offset": [
                0.1,
                8.6,
                0.2
              ],
              "lookAtYOffset": 0.05
            },
            {
              "zoom": 1.08,
              "duration": 420,
              "holdDuration": 420,
              "returnDuration": 360,
              "offset": [
                3.6,
                6,
                -4
              ],
              "lookAtYOffset": 0.1
            }
          ]
        },
        "overlay": [
          {
            "effect": "monochrome",
            "duration": 2000,
            "intensity": 1,
            "fadeIn": 600,
            "hold": 800,
            "fadeOut": 600,
            "phase": "rewind"
          },
          {
            "effect": "color-burst",
            "color": "#2ecc71",
            "duration": 600,
            "intensity": 0.8,
            "fadeIn": 0,
            "hold": 0,
            "fadeOut": 600,
            "phase": "restore"
          }
        ],
        "vfx": {
          "afterimageTrails": true,
          "afterimageCount": 8,
          "trailColor": "#3498db",
          "trailOpacity": 0.6,
          "rewindParticles": 64,
          "glowColor": "#3498db",
          "glowIntensity": 0.7
        },
        "sound": {
          "timewarp": "arcana:time_travel_warp",
          "rewind": "arcana:time_travel_rewind",
          "complete": "arcana:time_travel_complete"
        },
        "phases": [
          {
            "name": "camera_ascend",
            "duration": 800,
            "actions": [
              "camera_move",
              "sound_timewarp"
            ]
          },
          {
            "name": "rewind_pieces",
            "duration": 1600,
            "actions": [
              "vfx_afterimage_trails",
              "vfx_rewind_animation",
              "overlay_monochrome",
              "sound_rewind"
            ],
            "delay": 400
          },
          {
            "name": "color_restore",
            "duration": 800,
            "actions": [
              "overlay_color_restore"
            ],
            "delay": 0
          },
          {
            "name": "camera_return",
            "duration": 800,
            "actions": [
              "sound_complete"
            ]
          }
        ]
      }
    },
    "isCutscene": true,
    "canAnimatePiece": true,
    "rarity": "legendary",
    "category": "utility",
    "soundId": "arcana:time_travel"
  },
  "description": "Reverse the last two moves."
};
