// Auto-generated by Arcana Studio.
export const STUDIO_CARD_OVERRIDE = {
  "version": 1,
  "id": "time_freeze",
  "name": "time freeze",
  "durationMs": 2500,
  "settings": {
    "autoKey": true,
    "fps": 60,
    "timelineSnapMs": 50,
    "randomSeed": 1337,
    "seedLocked": true
  },
  "board": {
    "fen": "8/8/8/8/8/8/8/8 w - - 0 1",
    "focusSquare": null
  },
  "tracks": {
    "camera": [
      {
        "id": "cam_8fk8rz1y",
        "name": "Main Camera",
        "keys": [
          {
            "id": "camk_3ruap0no",
            "timeMs": 0,
            "position": [
              0.000002465559684440211,
              2.465544676576495,
              -2.1596604770232984e-8
            ],
            "target": [
              0,
              0,
              0
            ],
            "rotation": [
              -1.5707963355542616,
              0.0000010000060867711437,
              1.5795554140702714
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "camk_bvoe3ya4",
            "timeMs": 1250,
            "position": [
              0.000008183259228942123,
              8.183542175573779,
              6.805094689293432e-8
            ],
            "target": [
              0,
              0,
              0
            ],
            "rotation": [
              -1.570796318479311,
              9.999654247973556e-7,
              1.5624806451826099
            ],
            "fov": 55,
            "easing": "easeInOutQuad",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          },
          {
            "id": "camk_rt4dl0lo",
            "timeMs": 2500,
            "position": [
              -6.535074453730393e-8,
              22.376793242791944,
              -0.000022382660347363654
            ],
            "target": [
              0,
              0,
              0
            ],
            "rotation": [
              -1.5707973270570927,
              -2.920469605949619e-9,
              -3.1386729578152006
            ],
            "fov": 55,
            "easing": "easeInOutCubic",
            "bezier": [
              0.25,
              0.1,
              0.25,
              1
            ],
            "blendMode": "curve"
          }
        ]
      }
    ],
    "objects": [
      {
        "id": "obj_zvfiiefy",
        "name": "Main Piece",
        "type": "piece",
        "pieceSquare": "e4",
        "previewPlayAnimation": false,
        "attach": {
          "mode": "follow",
          "targetId": null,
          "parentId": null,
          "offset": [
            0,
            0,
            0
          ],
          "parenting": true
        },
        "keys": [],
        "pieceType": "p",
        "pieceColor": "white",
        "isAnimatablePiece": true
      }
    ],
    "particles": [],
    "overlays": [],
    "sounds": [
      {
        "id": "legacy_sound",
        "name": "Legacy Sound",
        "keys": [
          {
            "id": "snd_0",
            "timeMs": 0,
            "soundId": "arcana:time_freeze_freeze",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_1",
            "timeMs": 400,
            "soundId": "arcana:time_freeze_ambient",
            "volume": 1,
            "loop": false,
            "pitch": 1
          },
          {
            "id": "snd_2",
            "timeMs": 1600,
            "soundId": "arcana:time_freeze_unfreeze",
            "volume": 1,
            "loop": false,
            "pitch": 1
          }
        ]
      }
    ],
    "events": [
      {
        "id": "legacy_events",
        "name": "Legacy Events",
        "keys": [
          {
            "id": "evt_0_0",
            "timeMs": 0,
            "type": "camera:focus",
            "delayMs": 0,
            "payload": {
              "phase": "camera_focus",
              "cardId": "time_freeze",
              "legacyAction": "camera_move",
              "anchor": "target",
              "duration": 400,
              "holdDuration": 1800,
              "returnDuration": 400,
              "lookAtYOffset": 0.12,
              "soundMap": {
                "freeze": "arcana:time_freeze_freeze",
                "ambient": "arcana:time_freeze_ambient",
                "unfreeze": "arcana:time_freeze_unfreeze"
              }
            }
          },
          {
            "id": "evt_0_1",
            "timeMs": 0,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "camera_focus",
              "cardId": "time_freeze",
              "legacyAction": "sound_freeze",
              "soundId": "arcana:time_freeze_freeze",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "freeze": "arcana:time_freeze_freeze",
                "ambient": "arcana:time_freeze_ambient",
                "unfreeze": "arcana:time_freeze_unfreeze"
              }
            }
          },
          {
            "id": "evt_1_0",
            "timeMs": 400,
            "type": "vfx:play",
            "delayMs": 0,
            "payload": {
              "phase": "frozen_state",
              "cardId": "time_freeze",
              "legacyAction": "vfx_particles",
              "effect": "particles",
              "durationMs": 900,
              "soundMap": {
                "freeze": "arcana:time_freeze_freeze",
                "ambient": "arcana:time_freeze_ambient",
                "unfreeze": "arcana:time_freeze_unfreeze"
              }
            }
          },
          {
            "id": "evt_1_1",
            "timeMs": 400,
            "type": "overlay:monochrome",
            "delayMs": 0,
            "payload": {
              "phase": "frozen_state",
              "cardId": "time_freeze",
              "legacyAction": "overlay_monochrome",
              "duration": 700,
              "soundMap": {
                "freeze": "arcana:time_freeze_freeze",
                "ambient": "arcana:time_freeze_ambient",
                "unfreeze": "arcana:time_freeze_unfreeze"
              }
            }
          },
          {
            "id": "evt_1_2",
            "timeMs": 400,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "frozen_state",
              "cardId": "time_freeze",
              "legacyAction": "sound_ambient_loop",
              "soundId": "arcana:time_freeze_ambient",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "freeze": "arcana:time_freeze_freeze",
                "ambient": "arcana:time_freeze_ambient",
                "unfreeze": "arcana:time_freeze_unfreeze"
              }
            }
          },
          {
            "id": "evt_2_0",
            "timeMs": 1600,
            "type": "sound_play",
            "delayMs": 0,
            "payload": {
              "phase": "camera_return",
              "cardId": "time_freeze",
              "legacyAction": "sound_unfreeze",
              "soundId": "arcana:time_freeze_unfreeze",
              "volume": 1,
              "pitch": 1,
              "loop": false,
              "soundMap": {
                "freeze": "arcana:time_freeze_freeze",
                "ambient": "arcana:time_freeze_ambient",
                "unfreeze": "arcana:time_freeze_unfreeze"
              }
            }
          }
        ]
      }
    ]
  },
  "meta": {
    "source": "legacy-import",
    "createdAt": 1776121797901,
    "updatedAt": 1776122349246,
    "usedPieces": [],
    "legacyId": "time_freeze",
    "legacyImportedAt": 1776121797901,
    "legacyConfigSnapshot": {
      "id": "time_freeze",
      "duration": 4300,
      "config": {
        "camera": {
          "targetZoom": 1.3,
          "duration": 400,
          "holdDuration": 1800,
          "easing": "easeInOutCubic",
          "shots": [
            {
              "zoom": 1.45,
              "duration": 520,
              "holdDuration": 620,
              "returnDuration": 500,
              "offset": [
                3.4,
                5,
                3.1
              ],
              "lookAtYOffset": 0.12
            },
            {
              "zoom": 1.15,
              "duration": 560,
              "holdDuration": 760,
              "returnDuration": 520,
              "offset": [
                0.2,
                6.1,
                0.3
              ],
              "lookAtYOffset": 0.08
            },
            {
              "zoom": 1.35,
              "duration": 460,
              "holdDuration": 520,
              "returnDuration": 460,
              "offset": [
                -3,
                4.7,
                -2.7
              ],
              "lookAtYOffset": 0.12
            }
          ]
        },
        "overlay": {
          "effect": "monochrome",
          "duration": 2000,
          "intensity": 0.85,
          "fadeIn": 400,
          "hold": 1200,
          "fadeOut": 400
        },
        "vfx": {
          "snowParticles": 32,
          "particleVelocity": 0.5,
          "glow": true,
          "glowColor": "#4db8ff",
          "glowIntensity": 0.6
        },
        "sound": {
          "freeze": "arcana:time_freeze_freeze",
          "ambient": "arcana:time_freeze_ambient",
          "unfreeze": "arcana:time_freeze_unfreeze"
        },
        "phases": [
          {
            "name": "camera_focus",
            "duration": 400,
            "actions": [
              "camera_move",
              "sound_freeze"
            ]
          },
          {
            "name": "frozen_state",
            "duration": 1200,
            "actions": [
              "vfx_particles",
              "overlay_monochrome",
              "sound_ambient_loop"
            ],
            "delay": 0
          },
          {
            "name": "camera_return",
            "duration": 800,
            "actions": [
              "sound_unfreeze"
            ]
          }
        ]
      }
    },
    "isCutscene": true,
    "canAnimatePiece": true,
    "rarity": "legendary",
    "category": "defense",
    "soundId": "arcana:time_freeze"
  },
  "description": "Skip opponent's next turn entirely. On their following turn, they must make a board move before using or drawing Arcana."
};
