// Auto-generated by Arcana Studio.
import { STUDIO_CARD_OVERRIDE as card_astral_rebirth } from './cards/astral_rebirth.js';
import { STUDIO_CARD_OVERRIDE as card_execution } from './cards/execution.js';
import { STUDIO_CARD_OVERRIDE as card_mind_control } from './cards/mind_control.js';
import { STUDIO_CARD_OVERRIDE as card_promotion_ritual } from './cards/promotion_ritual.js';
import { STUDIO_CARD_OVERRIDE as card_shield_pawn } from './cards/shield_pawn.js';
import { STUDIO_CARD_OVERRIDE as card_time_freeze } from './cards/time_freeze.js';
import { STUDIO_CARD_OVERRIDE as card_time_travel } from './cards/time_travel.js';

export const STUDIO_CARD_OVERRIDES = {
  "astral_rebirth": card_astral_rebirth,
  "execution": card_execution,
  "mind_control": card_mind_control,
  "promotion_ritual": card_promotion_ritual,
  "shield_pawn": card_shield_pawn,
  "time_freeze": card_time_freeze,
  "time_travel": card_time_travel,
};

export const STUDIO_CUTSCENE_OVERRIDES = STUDIO_CARD_OVERRIDES;
