// Auto-generated by Arcana Studio.
import { STUDIO_CARD_OVERRIDE as card_antidote } from './cards/antidote.js';
import { STUDIO_CARD_OVERRIDE as card_astral_rebirth } from './cards/astral_rebirth.js';
import { STUDIO_CARD_OVERRIDE as card_chaos_theory } from './cards/chaos_theory.js';
import { STUDIO_CARD_OVERRIDE as card_execution } from './cards/execution.js';
import { STUDIO_CARD_OVERRIDE as card_filtered_cycle } from './cards/filtered_cycle.js';
import { STUDIO_CARD_OVERRIDE as card_fog_of_war } from './cards/fog_of_war.js';
import { STUDIO_CARD_OVERRIDE as card_mind_control } from './cards/mind_control.js';
import { STUDIO_CARD_OVERRIDE as card_pawn_guard } from './cards/pawn_guard.js';
import { STUDIO_CARD_OVERRIDE as card_peek_card } from './cards/peek_card.js';
import { STUDIO_CARD_OVERRIDE as card_poison_touch } from './cards/poison_touch.js';
import { STUDIO_CARD_OVERRIDE as card_pot_of_greed } from './cards/pot_of_greed.js';
import { STUDIO_CARD_OVERRIDE as card_promotion_ritual } from './cards/promotion_ritual.js';
import { STUDIO_CARD_OVERRIDE as card_shield_pawn } from './cards/shield_pawn.js';
import { STUDIO_CARD_OVERRIDE as card_time_freeze } from './cards/time_freeze.js';
import { STUDIO_CARD_OVERRIDE as card_time_travel } from './cards/time_travel.js';

export const STUDIO_CARD_OVERRIDES = {
  "antidote": card_antidote,
  "astral_rebirth": card_astral_rebirth,
  "chaos_theory": card_chaos_theory,
  "execution": card_execution,
  "filtered_cycle": card_filtered_cycle,
  "fog_of_war": card_fog_of_war,
  "mind_control": card_mind_control,
  "pawn_guard": card_pawn_guard,
  "peek_card": card_peek_card,
  "poison_touch": card_poison_touch,
  "pot_of_greed": card_pot_of_greed,
  "promotion_ritual": card_promotion_ritual,
  "shield_pawn": card_shield_pawn,
  "time_freeze": card_time_freeze,
  "time_travel": card_time_travel,
};

export const STUDIO_CUTSCENE_OVERRIDES = STUDIO_CARD_OVERRIDES;
