import fs from 'fs/promises';
import path from 'path';
import { pathToFileURL } from 'url';

export function getStudioSharedRoot(repoRoot) {
  return path.resolve(repoRoot, 'shared/arcana/studio');
}

export function getStudioCardsRoot(repoRoot) {
  return path.join(getStudioSharedRoot(repoRoot), 'cards');
}

export function getStudioOverridesIndexPath(repoRoot) {
  return path.join(getStudioSharedRoot(repoRoot), 'studioCutsceneOverrides.js');
}

function sanitizeFileStem(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'card';
}

function toModuleSource(card) {
  return [
    '// Auto-generated by Arcana Studio.',
    `export const STUDIO_CARD_OVERRIDE = ${JSON.stringify(card, null, 2)};`,
    '',
  ].join('\n');
}

export async function writeStudioCardModule(repoRoot, card) {
  if (!card || typeof card !== 'object') {
    throw new Error('Cannot write empty studio card');
  }

  const id = String(card.id || '').trim();
  if (!id) {
    throw new Error('Studio card is missing an id');
  }

  const cardsRoot = getStudioCardsRoot(repoRoot);
  await fs.mkdir(cardsRoot, { recursive: true });

  const fileStem = sanitizeFileStem(id);
  const filePath = path.join(cardsRoot, `${fileStem}.js`);
  await fs.writeFile(filePath, toModuleSource(card), 'utf8');
  return { filePath, fileStem, id };
}

export async function rebuildStudioOverridesIndex(repoRoot) {
  const cardsRoot = getStudioCardsRoot(repoRoot);
  const indexPath = getStudioOverridesIndexPath(repoRoot);
  await fs.mkdir(cardsRoot, { recursive: true });

  let entries = [];
  try {
    entries = await fs.readdir(cardsRoot, { withFileTypes: true });
  } catch {
    entries = [];
  }

  const cardFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.js'))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  const imports = [];
  const mapEntries = [];
  const cacheBust = `v=${Date.now()}`;

  for (const fileName of cardFiles) {
    const fileStem = fileName.replace(/\.js$/, '');
    const moduleUrl = `${pathToFileURL(path.join(cardsRoot, fileName)).href}?${cacheBust}`;
    const module = await import(moduleUrl);
    const card = module?.STUDIO_CARD_OVERRIDE;
    const cardId = String(card?.id || fileStem).trim();
    const alias = `card_${sanitizeFileStem(cardId)}`;

    imports.push(`import { STUDIO_CARD_OVERRIDE as ${alias} } from './cards/${fileName}';`);
    mapEntries.push(`  ${JSON.stringify(cardId)}: ${alias},`);
  }

  const content = [
    '// Auto-generated by Arcana Studio.',
    ...imports,
    '',
    'export const STUDIO_CARD_OVERRIDES = {',
    ...mapEntries,
    '};',
    '',
    'export const STUDIO_CUTSCENE_OVERRIDES = STUDIO_CARD_OVERRIDES;',
    '',
  ].join('\n');

  await fs.mkdir(path.dirname(indexPath), { recursive: true });
  await fs.writeFile(indexPath, content, 'utf8');
  return indexPath;
}

export async function removeFiles(files = []) {
  for (const filePath of files) {
    try {
      await fs.unlink(filePath);
    } catch {
      // Ignore missing or locked files.
    }
  }
}