export const ARCANA_DEFINITIONS = [
  // DEFENSIVE ARCANA
  {
    id: 'shield_pawn',
    name: 'Shield Pawn',
    rarity: 'common',
    category: 'Defense',
    description: 'Grant a pawn temporary protection for one enemy turn.',
    visual: 'Minimal glow around the pawn.',
  },
  {
    id: 'iron_fortress',
    name: 'Iron Fortress',
    rarity: 'uncommon',
    category: 'Defense',
    description: 'Make your king immune to checks for one turn.',
    visual: 'Metallic shield surrounding the king.',
  },
  {
    id: 'bishops_blessing',
    name: "Bishop's Blessing",
    rarity: 'rare',
    category: 'Defense',
    description: 'Prevent any piece on a diagonal from your bishop from being captured this turn.',
    visual: 'Golden diagonal rays emanating from bishop.',
  },
  {
    id: 'time_freeze',
    name: 'Time Freeze',
    rarity: 'legendary',
    category: 'Defense',
    description: 'Skip opponent\'s next turn entirely.',
    visual: 'Clock particles freezing around the board.',
  },
  
  // MOVEMENT ARCANA
  {
    id: 'spectral_march',
    name: 'Spectral March',
    rarity: 'uncommon',
    category: 'Movement',
    description: 'Allow a rook to pass through one friendly piece this turn.',
    visual: 'Ghostly trail as the rook moves.',
  },
  {
    id: 'knight_of_storms',
    name: 'Knight of Storms',
    rarity: 'rare',
    category: 'Movement',
    description: 'Teleport a knight to any legal square with a burst of lightning.',
    visual: 'Lightning particles on origin and destination.',
  },
  {
    id: 'queens_gambit',
    name: "Queen's Gambit",
    rarity: 'rare',
    category: 'Movement',
    description: 'Your queen can move twice this turn.',
    visual: 'Purple afterimage trail behind queen.',
  },
  {
    id: 'phantom_step',
    name: 'Phantom Step',
    rarity: 'uncommon',
    category: 'Movement',
    description: 'Any piece can move like a knight for one turn.',
    visual: 'Ghostly L-shaped arrows showing possible moves.',
  },
  {
    id: 'royal_swap',
    name: 'Royal Swap',
    rarity: 'epic',
    category: 'Movement',
    description: 'Swap positions of your king and any friendly piece.',
    visual: 'Swirling portal between the two pieces.',
  },
  {
    id: 'pawn_rush',
    name: 'Pawn Rush',
    rarity: 'common',
    category: 'Movement',
    description: 'All your pawns can move two squares this turn, even if already moved.',
    visual: 'Speed lines behind pawns.',
  },
  
  // OFFENSIVE ARCANA
  {
    id: 'double_strike',
    name: 'Double Strike',
    rarity: 'rare',
    category: 'Offense',
    description: 'Capture two enemy pieces in one turn with the same piece.',
    visual: 'Red slashing effect on captures.',
  },
  {
    id: 'poison_touch',
    name: 'Poison Touch',
    rarity: 'uncommon',
    category: 'Offense',
    description: 'Next piece you capture also removes an adjacent enemy piece.',
    visual: 'Green poison cloud spreading to adjacent square.',
  },
  {
    id: 'sharpshooter',
    name: 'Sharpshooter',
    rarity: 'epic',
    category: 'Offense',
    description: 'Your bishop can capture any piece on its diagonals, ignoring pieces in between.',
    visual: 'Laser beam from bishop to target.',
  },
  {
    id: 'berserker_rage',
    name: 'Berserker Rage',
    rarity: 'rare',
    category: 'Offense',
    description: 'Your rook deals damage to all pieces in its path when moving.',
    visual: 'Fire trail destroying pieces in path.',
  },
  {
    id: 'execution',
    name: 'Execution',
    rarity: 'legendary',
    category: 'Offense',
    description: 'Instantly remove any enemy piece of your choice (except king).',
    visual: 'Lightning bolt striking the piece from above.',
  },
  
  // RESURRECTION / TRANSFORMATION
  {
    id: 'astral_rebirth',
    name: 'Astral Rebirth',
    rarity: 'legendary',
    category: 'Resurrection',
    description: 'Resurrect a captured piece onto your back rank.',
    visual: 'Column of light and a short cutscene as the piece reforms.',
  },
  {
    id: 'necromancy',
    name: 'Necromancy',
    rarity: 'epic',
    category: 'Resurrection',
    description: 'Revive up to two captured pawns.',
    visual: 'Dark purple smoke as pawns rise from the void.',
  },
  {
    id: 'promotion_ritual',
    name: 'Promotion Ritual',
    rarity: 'uncommon',
    category: 'Transformation',
    description: 'Instantly promote any pawn to a queen regardless of position.',
    visual: 'Golden transformation particles.',
  },
  {
    id: 'metamorphosis',
    name: 'Metamorphosis',
    rarity: 'rare',
    category: 'Transformation',
    description: 'Transform any of your pieces into a different piece type (not king).',
    visual: 'Swirling multicolor vortex around the piece.',
  },
  {
    id: 'mirror_image',
    name: 'Mirror Image',
    rarity: 'epic',
    category: 'Transformation',
    description: 'Create a duplicate of one of your pieces (lasts 3 turns).',
    visual: 'Shimmering clone appearing next to original.',
  },
  
  // TACTICAL / UTILITY
  {
    id: 'vision',
    name: 'Vision',
    rarity: 'common',
    category: 'Utility',
    description: 'See all opponent\'s possible moves for this turn.',
    visual: 'Glowing outlines on all enemy pieces.',
  },
  {
    id: 'fog_of_war',
    name: 'Fog of War',
    rarity: 'uncommon',
    category: 'Utility',
    description: 'Hide your piece positions from opponent for one turn.',
    visual: 'Misty fog covering your side of the board.',
  },
  {
    id: 'cursed_square',
    name: 'Cursed Square',
    rarity: 'rare',
    category: 'Utility',
    description: 'Mark a square - any piece that lands there is destroyed.',
    visual: 'Pulsing red pentagram on the square.',
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    rarity: 'uncommon',
    category: 'Utility',
    description: 'Designate one square as safe - no captures can occur there for 2 turns.',
    visual: 'Protective blue dome over the square.',
  },
  {
    id: 'time_travel',
    name: 'Time Travel',
    rarity: 'legendary',
    category: 'Utility',
    description: 'Undo the last two moves (yours and opponent\'s).',
    visual: 'Clock rewinding animation.',
  },
  {
    id: 'chaos_theory',
    name: 'Chaos Theory',
    rarity: 'epic',
    category: 'Utility',
    description: 'Randomly shuffle 3 pieces on each side to different positions.',
    visual: 'Swirling chaos vortex moving pieces.',
  },
  {
    id: 'mind_control',
    name: 'Mind Control',
    rarity: 'legendary',
    category: 'Utility',
    description: 'Take control of an enemy piece for one turn.',
    visual: 'Purple tendrils wrapping around enemy piece.',
  },
  {
    id: 'sacrifice',
    name: 'Sacrifice',
    rarity: 'rare',
    category: 'Utility',
    description: 'Destroy one of your pieces to gain two random arcana.',
    visual: 'Piece dissolving into magical energy.',
  },
  
  // ADVANCED COMBINATIONS
  {
    id: 'en_passant_master',
    name: 'En Passant Master',
    rarity: 'uncommon',
    category: 'Special',
    description: 'All your pawns can perform en passant on any adjacent enemy pawn.',
    visual: 'Highlighted capture zones around pawns.',
  },
  {
    id: 'castle_breaker',
    name: 'Castle Breaker',
    rarity: 'rare',
    category: 'Offense',
    description: 'Destroy enemy rook and disable their ability to castle.',
    visual: 'Crumbling castle animation on rook.',
  },
  {
    id: 'divine_intervention',
    name: 'Divine Intervention',
    rarity: 'legendary',
    category: 'Defense',
    description: 'Automatically block the next checkmate attempt against you.',
    visual: 'Angelic wings shielding your king.',
  },
  {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    rarity: 'epic',
    category: 'Offense',
    description: 'Capture bounces to adjacent enemy pieces (up to 3 total).',
    visual: 'Lightning arcing between captured pieces.',
  },
  {
    id: 'temporal_echo',
    name: 'Temporal Echo',
    rarity: 'rare',
    category: 'Movement',
    description: 'Repeat your last move with a different piece.',
    visual: 'Ghostly afterimage of previous move.',
  },
];
