export const ARCANA_DEFINITIONS = [
  // DEFENSIVE ARCANA
  {
    id: 'shield_pawn',
    name: 'Shield Pawn',
    rarity: 'common',
    category: 'defense',
    description: 'Select a pawn to grant temporary protection: it cannot be captured for one enemy turn.',
    visual: { particles: false, animation: false, cutscene: false },
  },
  {
    id: 'iron_fortress',
    name: 'Iron Fortress',
    rarity: 'uncommon',
    category: 'defense',
    description: 'Make your king immune to checks for one turn.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'bishops_blessing',
    name: "Bishop's Blessing",
    rarity: 'rare',
    category: 'defense',
    description: 'Prevent any piece on a diagonal from your bishop from being captured this turn.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'time_freeze',
    name: 'Time Freeze',
    rarity: 'legendary',
    category: 'defense',
    description: 'Skip opponent\'s next turn entirely.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  
  // MOVEMENT ARCANA
  {
    id: 'spectral_march',
    name: 'Spectral March',
    rarity: 'uncommon',
    category: 'movement',
    description: 'Allow a rook to pass through one friendly piece this turn.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'knight_of_storms',
    name: 'Knight of Storms',
    rarity: 'rare',
    category: 'movement',
    description: 'Teleport a knight to any legal square, accompanied by a storm of energy.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'queens_gambit',
    name: "Queen's Gambit",
    rarity: 'rare',
    category: 'movement',
    description: 'Your queen can move twice this turn.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'phantom_step',
    name: 'Phantom Step',
    rarity: 'uncommon',
    category: 'movement',
    description: 'Any piece can move like a knight for one turn.',
    visual: { particles: true, animation: false, cutscene: false },
  },
  {
    id: 'royal_swap',
    name: 'Royal Swap',
    rarity: 'epic',
    category: 'movement',
    description: 'Select any of your pieces to swap positions with your king.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'pawn_rush',
    name: 'Pawn Rush',
    rarity: 'common',
    category: 'movement',
    description: 'All your pawns can move two squares this turn, even if already moved.',
    visual: { particles: true, animation: false, cutscene: false },
  },
  
  // OFFENSIVE ARCANA
  {
    id: 'double_strike',
    name: 'Double Strike',
    rarity: 'rare',
    category: 'offense',
    description: 'Capture two enemy pieces in one turn with the same piece.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'poison_touch',
    name: 'Poison Touch',
    rarity: 'uncommon',
    category: 'offense',
    description: 'Next piece you capture also removes an adjacent enemy piece.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'sharpshooter',
    name: 'Sharpshooter',
    rarity: 'epic',
    category: 'offense',
    description: 'Your bishop can capture any piece on its diagonals, ignoring pieces in between.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'berserker_rage',
    name: 'Berserker Rage',
    rarity: 'rare',
    category: 'offense',
    description: 'Your rook deals damage to all pieces in its path when moving.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'execution',
    name: 'Execution',
    rarity: 'legendary',
    category: 'offense',
    description: 'Select and instantly remove any enemy piece of your choice (except king).',
    visual: { particles: true, animation: true, cutscene: true },
  },
  
  // RESURRECTION / TRANSFORMATION
  {
    id: 'astral_rebirth',
    name: 'Astral Rebirth',
    rarity: 'legendary',
    category: 'resurrection',
    description: 'Resurrect one captured piece onto your back rank.',
    visual: { particles: true, animation: true, cutscene: true },
  },
  {
    id: 'necromancy',
    name: 'Necromancy',
    rarity: 'epic',
    category: 'resurrection',
    description: 'Revive up to two captured pawns.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'promotion_ritual',
    name: 'Promotion Ritual',
    rarity: 'uncommon',
    category: 'transformation',
    description: 'Select any of your pawns to instantly promote it to a queen regardless of position.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'metamorphosis',
    name: 'Metamorphosis',
    rarity: 'rare',
    category: 'transformation',
    description: 'Select one of your pieces to transform it into a different piece type (not king).',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'mirror_image',
    name: 'Mirror Image',
    rarity: 'epic',
    category: 'transformation',
    description: 'Select one of your pieces to create a duplicate of it (lasts 3 turns).',
    visual: { particles: true, animation: true, cutscene: false },
  },
  
  // TACTICAL / UTILITY
  {
    id: 'vision',
    name: 'Vision',
    rarity: 'common',
    category: 'utility',
    description: 'See all opponent\'s possible moves for this turn.',
    visual: { particles: false, animation: false, cutscene: false },
  },
  {
    id: 'fog_of_war',
    name: 'Fog of War',
    rarity: 'uncommon',
    category: 'utility',
    description: 'Hide your piece positions from opponent for one turn.',
    visual: { particles: true, animation: false, cutscene: false },
  },
  {
    id: 'cursed_square',
    name: 'Cursed Square',
    rarity: 'rare',
    category: 'utility',
    description: 'Select a square to mark it as cursed - any piece that lands there is destroyed.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    rarity: 'uncommon',
    category: 'utility',
    description: 'Select a square to designate it as safe - no captures can occur there for 2 turns.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'time_travel',
    name: 'Time Travel',
    rarity: 'legendary',
    category: 'utility',
    description: 'Undo the last two moves (yours and opponent\'s).',
    visual: { particles: true, animation: true, cutscene: true },
  },
  {
    id: 'chaos_theory',
    name: 'Chaos Theory',
    rarity: 'epic',
    category: 'utility',
    description: 'Randomly shuffle 3 pieces on each side to different positions.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'mind_control',
    name: 'Mind Control',
    rarity: 'legendary',
    category: 'utility',
    description: 'Select an enemy piece to take control of it for one turn.',
    visual: { particles: true, animation: true, cutscene: true },
  },
  {
    id: 'sacrifice',
    name: 'Sacrifice',
    rarity: 'rare',
    category: 'utility',
    description: 'Select one of your pieces to destroy it and gain two random arcana.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  
  // ADVANCED COMBINATIONS
  {
    id: 'en_passant_master',
    name: 'En Passant Master',
    rarity: 'uncommon',
    category: 'special',
    description: 'All your pawns can perform en passant on any adjacent enemy pawn.',
    visual: { particles: false, animation: false, cutscene: false },
  },
  {
    id: 'castle_breaker',
    name: 'Castle Breaker',
    rarity: 'rare',
    category: 'offense',
    description: 'Destroy enemy rook and disable their ability to castle.',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'divine_intervention',
    name: 'Divine Intervention',
    rarity: 'legendary',
    category: 'defense',
    description: 'Automatically block the next checkmate attempt against you.',
    visual: { particles: true, animation: true, cutscene: true },
  },
  {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    rarity: 'epic',
    category: 'offense',
    description: 'Capture bounces to adjacent enemy pieces (up to 3 total).',
    visual: { particles: true, animation: true, cutscene: false },
  },
  {
    id: 'temporal_echo',
    name: 'Temporal Echo',
    rarity: 'rare',
    category: 'movement',
    description: 'Repeat your last move with a different piece.',
    visual: { particles: true, animation: true, cutscene: false },
  },
];
