export const ARCANA_DEFINITIONS = [
  // DEFENSIVE ARCANA - COMMON
  {
    id: 'shield_pawn',
    name: 'Shield Pawn',
    rarity: 'common',
    category: 'defense',
    description: 'Select a pawn to grant temporary protection: it cannot be captured for one enemy turn.',
    visual: { particles: false, animation: true, cutscene: false },
    visualLifecycle: { mode: 'untilTurnEnd', autoClearOnServerTurnEnd: true },
    // soundId: 'arcana:shield',
  },
  {
    id: 'squire_support',
    name: 'Squire Support',
    rarity: 'uncommon',
    category: 'defense',
    description: 'Choose a piece. If it would be captured on the opponent\'s next move, it instead survives with the attacker bouncing back one square.',
    visual: { particles: true, animation: true, cutscene: false },
    visualLifecycle: { mode: 'clientOnly', duration: 'untilOpponentTurn' },
    // soundId: 'arcana:squire_support',
  },
  {
    id: 'pawn_guard',
    name: 'Pawn Guard',
    rarity: 'common',
    category: 'defense',
    description: 'Select a pawn. The first friendly piece immediately behind it in the same column is shielded for 1 turn (only that piece is protected).',
    visual: { particles: false, animation: true, cutscene: false },
    // soundId: 'arcana:pawn_guard',
  },
  {
    id: 'iron_fortress',
    name: 'Iron Fortress',
    rarity: 'rare',
    category: 'defense',
    description: 'All your pawns cannot be captured for one enemy turn.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:iron_fortress',
  },

  // DEFENSIVE ARCANA - RARE+
  {
    id: 'bishops_blessing',
    name: "Bishop's Blessing",
    rarity: 'rare',
    category: 'defense',
    description: 'Prevent any friendly piece on a diagonal from your bishop from being captured this turn.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:bishops_blessing',
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    rarity: 'rare',
    category: 'defense',
    description: 'Select a square to designate it as safe - no captures can occur there for 4 turns.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:sanctuary',
    endsTurn: true,
  },
  {
    id: 'time_freeze',
    name: 'Time Freeze',
    rarity: 'legendary',
    category: 'defense',
    description: 'Skip opponent\'s next turn entirely. On their following turn, they must make a board move before using or drawing Arcana.',
    visual: { particles: true, animation: true, cutscene: true },
    // soundId: 'arcana:time_freeze',
  },
  {
    id: 'divine_intervention',
    name: 'Divine Intervention',
    rarity: 'legendary',
    category: 'defense',
    description: 'Activate a one-time save. The next time your king is put in check, Divine Intervention spawns a blocker (or rescue piece) to cancel the check immediately.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:divine_intervention',
  },
  
  // MOVEMENT ARCANA - COMMON
  {
    id: 'pawn_rush',
    name: 'Pawn Rush',
    rarity: 'common',
    category: 'movement',
    description: 'All your pawns can move two squares this turn, even if already moved.',
    visual: { particles: false, animation: false, cutscene: false },
    // soundId: 'arcana:pawn_rush',
  },
  {
    id: 'soft_push',
    name: 'Soft Push',
    rarity: 'common',
    category: 'movement',
    description: 'Move any piece one square toward the center of the board. Must still be a legal move and cannot capture.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:soft_push',
  },

  // MOVEMENT ARCANA - UNCOMMON+
  {
    id: 'spectral_march',
    name: 'Spectral March',
    rarity: 'uncommon',
    category: 'movement',
    description: 'Allow a rook to pass through one friendly piece this turn.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:spectral_march',
  },
  {
    id: 'phantom_step',
    name: 'Phantom Step',
    rarity: 'uncommon',
    category: 'movement',
    description: 'Any piece can move like a knight for one turn.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:phantom_step',
  },
  {
    id: 'knight_of_storms',
    name: 'Knight of Storms',
    rarity: 'rare',
    category: 'movement',
    description: 'Move your knight to any square within a 2-square radius.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:knight_of_storms',
  },
  {
    id: 'temporal_echo',
    name: 'Temporal Echo',
    rarity: 'rare',
    category: 'movement',
    description: 'For this turn, all your pieces gain extra moves in the same direction as your last move, up to the same distance. Normal piece moves still work.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:temporal_echo',
  },
  {
    id: 'royal_swap',
    name: 'Royal Swap',
    rarity: 'epic',
    category: 'movement',
    description: 'Select one of your pawns to swap positions with your king.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:royal_swap',
    endsTurn: true,
  },
  {
    id: 'queens_gambit',
    name: "Queen's Gambit",
    rarity: 'epic',
    category: 'movement',
    description: 'Your queen can move twice this turn.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:queens_gambit',
  },
  
  // OFFENSIVE ARCANA - COMMON
  {
    id: 'focus_fire',
    name: 'Focus Fire',
    rarity: 'common',
    category: 'offense',
    description: 'If your next move is a capture, draw 1 additional common Arcana card after the capture resolves.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:arcane_cycle',
  },
  {
    id: 'pot_of_greed',
    name: 'Pot of Greed',
    rarity: 'epic',
    category: 'utility',
    description: 'Draw 3 additional cards from your deck. ("That\'s what it does")',
    visual: { particles: true, animation: false, cutscene: false },
    endsTurn: true,
  },

  // OFFENSIVE ARCANA - UNCOMMON+
  {
    id: 'poison_touch',
    name: 'Poison Touch',
    rarity: 'uncommon',
    category: 'offense',
    description: 'When you capture a piece, poison a random adjacent enemy piece. Poisoned pieces die after 6 turns if not healed with Antidote.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:poison_touch',
  },
  {
    id: 'double_strike',
    name: 'Double Strike',
    rarity: 'rare',
    category: 'offense',
    description: 'After capturing with one piece, a second piece must capture. If the second capture lands, that second piece returns to where it started (capture then retreat). If you cannot capture, your turn ends.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:double_strike',
  },
  {
    id: 'berserker_rage',
    name: 'Berserker Rage',
    rarity: 'rare',
    category: 'offense',
    description: 'After capturing, the same piece gets one more capture, and that second capture must land on a nonadjacent square to the first kill. If you cannot do this, your turn ends.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:berserker_rage',
  },
  {
    id: 'castle_breaker',
    name: 'Castle Breaker',
    rarity: 'rare',
    category: 'offense',
    description: 'Disable the opponent\'s ability to castle for 3 turns.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:castle_breaker',
  },
  {
    id: 'sacrifice',
    name: 'Sacrifice',
    rarity: 'rare',
    category: 'utility',
    description: 'Select one of your pieces to destroy it and gain 2 arcana cards (stronger piece = stronger cards).',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:sacrifice',
  },
  {
    id: 'sharpshooter',
    name: 'Sharpshooter',
    rarity: 'epic',
    category: 'offense',
    description: 'Your bishop can capture any piece on its diagonals, ignoring pieces in between.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:sharpshooter',
  },
  {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    rarity: 'epic',
    category: 'offense',
    description: 'Capture bounces to 1 adjacent enemy piece (cannot capture queens or kings).',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:chain_lightning',
  },
  {
    id: 'execution',
    name: 'Execution',
    rarity: 'legendary',
    category: 'offense',
    description: 'Select an enemy piece and destroy it.',
    visual: { particles: true, animation: true, cutscene: true },
    // soundId: 'arcana:execution',
    endsTurn: true,
  },
  
  // RESURRECTION / TRANSFORMATION - UNCOMMON+
  {
    id: 'necromancy',
    name: 'Necromancy',
    rarity: 'epic',
    category: 'resurrection',
    description: 'Revive up to two captured pawns.',
    visual: { particles: true, animation: true, cutscene: true },
    // soundId: 'arcana:necromancy',
    endsTurn: true,
  },
  {
    id: 'metamorphosis',
    name: 'Metamorphosis',
    rarity: 'rare',
    category: 'transformation',
    description: 'Select one of your pieces to transform it into a different piece type (not king or queen).',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:metamorphosis',
  },
  {
    id: 'mirror_image',
    name: 'Mirror Image',
    rarity: 'epic',
    category: 'transformation',
    description: 'Select one of your pieces to create a duplicate if there is a free square next to it (lasts 3 turns).',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:mirror_image',
  },
  {
    id: 'astral_rebirth',
    name: 'Astral Rebirth',
    rarity: 'legendary',
    category: 'resurrection',
    description: 'Resurrect up to 2 captured pieces onto your back rank. Higher-value pieces are revived first.',
    visual: { particles: true, animation: true, cutscene: true },
    // soundId: 'arcana:astral_rebirth',
    endsTurn: true,
  },
  {
    id: 'promotion_ritual',
    name: 'Promotion Ritual',
    rarity: 'legendary',
    category: 'transformation',
    description: 'Select a pawn and promote it to a queen. You gain 2 consecutive moves.',
    visual: { particles: true, animation: true, cutscene: true },
    // soundId: 'arcana:promotion_ritual',
    endsTurn: false,
  },
  
  // TACTICAL / UTILITY - COMMON
  {
    id: 'vision',
    name: 'Vision',
    rarity: 'common',
    category: 'utility',
    description: 'Only you can see all opponent move destinations for the rest of your current turn.',
    visual: { particles: false, animation: false, cutscene: false },
    // soundId: 'arcana:vision',
  },
  {
    id: 'line_of_sight',
    name: 'Line of Sight',
    rarity: 'common',
    category: 'utility',
    description: 'Only you can see one chosen piece\'s legal moves and hover risk preview for the rest of your current turn.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:line_of_sight',
  },
  {
    id: 'filtered_cycle',
    name: 'Filtered Cycle',
    rarity: 'common',
    category: 'utility',
    description: 'Choose a category and draw a weighted common/uncommon Arcana card from that category.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:filtered_cycle',
  },
  {
    id: 'quiet_thought',
    name: 'Quiet Thought',
    rarity: 'common',
    category: 'utility',
    description: 'Only you can see the pieces threatening your king for your next 3 turns.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:quiet_thought',
  },
  {
    id: 'map_fragments',
    name: 'Map Fragments',
    rarity: 'common',
    category: 'utility',
    description: 'Only you can see three strongest predicted enemy move targets for the rest of your current turn.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:map_fragments',
  },
  {
    id: 'peek_card',
    name: 'Peek Card',
    rarity: 'common',
    category: 'utility',
    description: 'Only you can see one chosen card from your opponent\'s hand.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:peek_card',
  },
  // TACTICAL / UTILITY - UNCOMMON+
  {
    id: 'fog_of_war',
    name: 'Fog of War',
    rarity: 'uncommon',
    category: 'utility',
    description: 'Hide your piece positions from opponent for one turn.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:fog_of_war',
  },
  {
    id: 'en_passant_master',
    name: 'En Passant Master',
    rarity: 'uncommon',
    category: 'utility',
    description: 'All your pawns can perform en passant on any adjacent enemy pawn.',
    visual: { particles: false, animation: false, cutscene: false },
    // soundId: 'arcana:en_passant_master',
  },
  {
    id: 'antidote',
    name: 'Antidote',
    rarity: 'common',
    category: 'utility',
    description: 'Select a poisoned piece to cleanse it and prevent its death. Can only target pieces with active poison.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:antidote',
  },
  {
    id: 'cursed_square',
    name: 'Cursed Square',
    rarity: 'rare',
    category: 'utility',
    description: 'Select a square to mark it as cursed - any piece that lands there is destroyed (lasts 4 turns).',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:cursed_square',
    endsTurn: true,
  },
  {
    id: 'chaos_theory',
    name: 'Chaos Theory',
    rarity: 'epic',
    category: 'utility',
    description: 'Randomly shuffle 3 pieces on each side to different positions.',
    visual: { particles: true, animation: false, cutscene: false },
    // soundId: 'arcana:chaos_theory',
    endsTurn: true,
  },
  {
    id: 'time_travel',
    name: 'Time Travel',
    rarity: 'legendary',
    category: 'utility',
    description: 'Reverse the last two moves.',
    visual: { particles: true, animation: false, cutscene: true },
    // soundId: 'arcana:time_travel',
    endsTurn: true,
  },
  {
    id: 'mind_control',
    name: 'Mind Control',
    rarity: 'legendary',
    category: 'utility',
    description: 'Select an enemy piece to seize control of it. On your next move, you must move that piece first before moving any of your own pieces. It cannot capture the king.',
    visual: { particles: true, animation: true, cutscene: true },
    // soundId: 'arcana:mind_control',
    endsTurn: false,
  },
  {
    id: 'breaking_point',
    name: 'Breaking Point',
    rarity: '???',
    category: 'special',
    description: 'Target an enemy non-king piece: destroy it. Adjacent enemy pieces are pushed 1 square directly away if possible, and each has a 50% chance to die from the shockwave. Kings cannot be killed by the shockwave but may be pushed if a free square exists.',
    visual: { particles: true, animation: true, cutscene: true },
    // soundId: 'arcana:breaking_point',
    iconPath: '/cards/icons/breaking-point.png',
    endsTurn: true,
  },
  {
    id: 'edgerunner_overdrive',
    name: 'Edgerunner Overdrive',
    rarity: '???',
    category: 'special',
    description: 'Target one of your non-pawn, non-king pieces. Pawns cannot be targeted by this card. It gets 1 move, and each capture grants 1 extra move (up to 5 total). After the sequence, the piece returns to its starting square. It cannot capture the king.',
    visual: { particles: true, animation: true, cutscene: false },
    // soundId: 'arcana:edgerunner_overdrive',
    backgroundPath: '/cards/backgrounds/Cyberpunk.png',
    iconPath: '/cards/icons/edgerunner-overdrive.png',
    endsTurn: false,
  }
];
